spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CarLoanDB;trustServerCertificate=true
    username: sa
    password: P@ssw0rd
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    

